<!-- selectbank Popup -->
<div class="popup selectbank">
	<header class="bar bar-nav">
		<a class="button button-link button-nav pull-right close-popup"><span class="icon close icon-close"></span></a>
		<h1 class="title">选择银行</h1>
	</header>
	<div class="content" data-toggle="scroller" data-type="js">
		<div class="content-inner">
			<div class="list-block media-list diy-list">
				<div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_ny.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">农业银行</div>
		            	<div class="item-subtitle color-gray">单笔/单日2万</div>
	            	</div>
			    </div>

			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_gs.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">工商银行</div>
		            	<div class="item-subtitle color-gray">单笔/单日5万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_zg.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">中国银行</div>
		            	<div class="item-subtitle color-gray">单笔5万/单日20万</div>
	            	</div>
			    </div>
				<div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_zs.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">招商银行</div>
		            	<div class="item-subtitle color-gray">单笔5万/单日50万</div>
	            	</div>
			    </div>
			    
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_js.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">建设银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日无限额</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_hx.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">华夏银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日100万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_zx.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">中信银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日100万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_gd.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">光大银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日100万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_ms.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">民生银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日100万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_gf.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">广发银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日无限额</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_pa.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">平安银行</div>
		            	<div class="item-subtitle color-gray">单笔50万/单日100万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_jt.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">交通银行</div>
		            	<div class="item-subtitle color-gray">单笔/单日5万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_xy.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">兴业银行</div>
		            	<div class="item-subtitle color-gray">单笔/单日5万</div>
	            	</div>
			    </div>
			    
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_sp.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">浦发银行</div>
		            	<div class="item-subtitle color-gray">单笔/单日5万</div>
	            	</div>
			    </div>
			    <div class="item-content item-link j-selectbank">
          			<div class="item-media"><img class="inline-img" src="{$HOST_STATIC}/licai/dist/common/img/bank_yz.png"></div>
			    	<div class="item-inner">
			    		<div class="item-title">邮政储蓄</div>
		            	<div class="item-subtitle color-gray">单笔/单日5千</div>
	            	</div>
			    </div>
			</div>
		</div>
	</div>
</div>
